<?php

namespace AppBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAddresses(){
//        Alias 'a' = Address

        $qb = $this->createQueryBuilder('a')
            ->select('a.address', 'a.city', 'a.id', 'a.nom', 'a.postal', 'a.lat', 'a.lng')
            ->orderBy('a.city', 'DESC');
        return $qb->getQuery()->getResult();
    }

}
