<?php

namespace AppBundle\Repository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMatches(){
//        Alias 'ca' = category
//        Alias 'fc' = calendar
//        Alias 'cb1' = club1
//        Alias 'cb2' = club2

        $qb = $this->createQueryBuilder('fc')
            ->select('fc.id', 'fc.start', 'fc.scores', 'fc.color')
            ->join ('fc.category', 'a')
            ->addSelect ( 'a.categoryName')
            ->leftJoin ('fc.club1', 'cb1')
            ->addSelect ( 'cb1.clubName')
            ->leftJoin ('fc.club2', 'cb2')
            ->addSelect ( 'cb2.clubName as clubName2');
//            ->orderBy('fc.start', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
