<?php

namespace AppBundle\Repository;

/**
 * CategoryGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
