<?php

namespace AppBundle\Repository;

/**
 * ClubsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubsRepository extends \Doctrine\ORM\EntityRepository
{
}
