<?php

namespace AppBundle\Repository;

/**
 * ClubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
