###########################################################
###########################################################
########################## VIEWS ##########################
###########################################################
###########################################################
app:
    resource: '@AppBundle/Controller/'
    type: annotation

###########################################################
###########################################################
######################### ADMIN ###########################
###########################################################
###########################################################

homeadmin:
    path:     /admin
    defaults: { _controller: "AppBundle:Default:homeAdmin" }
    methods:  GET

app_clubs:
    resource: "@AppBundle/Resources/config/routing/clubs.yml"
    prefix:   /clubs

app_categories:
    resource: "@AppBundle/Resources/config/routing/categories.yml"
    prefix:   /categories

app_groups:
    resource: "@AppBundle/Resources/config/routing/groups.yml"
    prefix:   /groups

app_clubcategory:
    resource: "@AppBundle/Resources/config/routing/clubcategory.yml"
    prefix:   /clubcategory

app_categorygroup:
    resource: "@AppBundle/Resources/config/routing/categorygroup.yml"
    prefix:   /categorygroup