###########################################################
###########################################################
########################## VIEWS ##########################
###########################################################
###########################################################
app:
    resource: '@AppBundle/Controller/'
    type: annotation

###########################################################
###########################################################
######################### ADMIN ###########################
###########################################################
###########################################################

app_clubs:
    resource: "@AppBundle/Resources/config/routing/clubs.yml"
    prefix:   /clubs

app_categories:
    resource: "@AppBundle/Resources/config/routing/categories.yml"
    prefix:   /categories

app_groups:
    resource: "@AppBundle/Resources/config/routing/groups.yml"
    prefix:   /groups