###########################################################
###########################################################
########################## VIEWS ##########################
###########################################################
###########################################################
app:
    resource: '@AppBundle/Controller/'
    type: annotation

###########################################################
###########################################################
######################### ADMIN ###########################
###########################################################
###########################################################

homeadmin:
    path:     /admin
    defaults: { _controller: "AppBundle:Default:homeAdmin" }
    methods:  GET
#    option:
#        expose: true

app_clubs:
    resource: "@AppBundle/Resources/config/routing/clubs.yml"
    prefix:   /clubs

app_categories:
    resource: "@AppBundle/Resources/config/routing/categories.yml"
    prefix:   /categories

app_groups:
    resource: "@AppBundle/Resources/config/routing/groups.yml"
    prefix:   /groups

app_clubcategory:
    resource: "@AppBundle/Resources/config/routing/clubcategory.yml"
    prefix:   /clubcategory

app_categorygroup:
    resource: "@AppBundle/Resources/config/routing/categorygroup.yml"
    prefix:   /categorygroup

app_address:
    resource: "@AppBundle/Resources/config/routing/address.yml"
    prefix:   /address

map_index:
    path:     /map
    defaults: { _controller: "AppBundle:Default:map" }
    methods:  GET

fullcalendar_index:
    path:     /fullcalendar
    defaults: { _controller: "AppBundle:Default:fullCalendar" }
    methods:  GET
    options:
        expose: true

app_calendar:
    resource: "@AppBundle/Resources/config/routing/calendar.yml"
    prefix:   /calendar
    options:
        expose: true

##########################################
########   Routes Calendrier   ###########
##########################################

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        expose: true

##########################################
############   FosJSRoutung   ############
##########################################

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix:   /

##########################################
##############   FosJUser   ##############
##########################################

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"