calendar_index:
    path:     /
    defaults: { _controller: "AppBundle:Calendar:index" }
    methods:  GET

calendar_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Calendar:show" }
    methods:  GET

calendar_new:
    path:     /new
    defaults: { _controller: "AppBundle:Calendar:new" }
    methods:  [GET, POST]

calendar_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Calendar:edit" }
    methods:  [GET, POST]

calendar_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Calendar:delete" }
    methods:  DELETE
