categorygroup_index:
    path:     /
    defaults: { _controller: "AppBundle:CategoryGroup:index" }
    methods:  GET

categorygroup_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CategoryGroup:show" }
    methods:  GET

categorygroup_new:
    path:     /new
    defaults: { _controller: "AppBundle:CategoryGroup:new" }
    methods:  [GET, POST]

categorygroup_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CategoryGroup:edit" }
    methods:  [GET, POST]

categorygroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CategoryGroup:delete" }
    methods:  DELETE
