#app_clubs:
#    resource: "@AppBundle/Resources/config/routing/clubs.yml"
#    prefix:   /clubs
#    option:
#        expose: true

##########################################
########   Routes Agenda Json  ###########
## Permet de convertir route php en js ###
##########################################

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix:   /

