AppBundle\Entity\Calendar:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CalendarRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start:
            type: datetime
        end:
            type: datetime
            nullable: true

    manyToOne:
        club1:
            targetEntity: AppBundle\Entity\ClubCategory
            inversedBy: calendar1
            joinColumn:
                name: club1_id
                referencedColumnName: id
        club2:
            targetEntity: AppBundle\Entity\ClubCategory
            inversedBy: calendar2
            joinColumn:
                name: club2_id
                referencedColumnName: id
        address:
            targetEntity: AppBundle\Entity\Address
            inversedBy: calendar3
            joinColumn:
                name: address_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
