AppBundle\Entity\Categories:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoriesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        categoryName:
            type: string
            length: 255
            column: category_name
            unique: true

    oneToMany:
        category:
            targetEntity: AppBundle\Entity\ClubCategory
            mappedBy: categories
    lifecycleCallbacks: {  }
