AppBundle\Entity\CategoryGroup:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryGroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        categoryId:
            type: integer
            column: category_id
        groupId:
            type: integer
            column: group_id

    manyToOne:
        categories:
            targetEntity: AppBundle\Entity\Categories
            inversedBy: categories
            joinColumn:
                name: category_id
                referencedColumnName: id
        group:
            targetEntity: AppBundle\Entity\Groups
            inversedBy: group
            joinColumn:
                name: group_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
