AppBundle\Entity\Clubs:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ClubsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        clubName:
            type: string
            length: 255
            column: club_name
            unique: true

    manyToMany:
        category:
            targetEntity: AppBundle\Entity\Categories
            joinTable:
                name: clubs_categories
                joinColumns:
                    clubs_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    categories_id:
                        referencedColumnName: id
                        unique: true
    lifecycleCallbacks: {  }
