AppBundle\Entity\Groups:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GroupsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        groupName:
            type: string
            length: 255
            column: group_name
            unique: true

#    oneToMany:
#        category:
#            targetEntity: AppBundle\Entity\ClubCategory
#            mappedBy: categories
    lifecycleCallbacks: {  }
